language: scala
scala: 2.12.8
script: eval "$SCRIPT"

env:
  - SCRIPT="cd play-java-chatroom-example        && scripts/test-sbt"
  - SCRIPT="cd play-java-compile-di-example      && scripts/test-sbt"
  - SCRIPT="cd play-java-dagger2-example         && scripts/test-sbt"
  - SCRIPT="cd play-java-ebean-example           && scripts/test-sbt"
  - SCRIPT="cd play-java-fileupload-example      && scripts/test-sbt"
  - SCRIPT="cd play-java-forms-example           && scripts/test-sbt"
  - SCRIPT="cd play-java-hello-world-tutorial    && scripts/test-sbt"
  - SCRIPT="cd play-java-jpa-example             && scripts/test-sbt"
  - SCRIPT="cd play-java-rest-api-example        && scripts/test-sbt"
  - SCRIPT="cd play-java-starter-example         && scripts/test-sbt"
  - SCRIPT="cd play-java-streaming-example       && scripts/test-sbt"
  - SCRIPT="cd play-java-websocket-example       && scripts/test-sbt"
  - SCRIPT="cd play-scala-anorm-example          && scripts/test-sbt"
  - SCRIPT="cd play-scala-chatroom-example       && scripts/test-sbt"
  - SCRIPT="cd play-scala-compile-di-example     && scripts/test-sbt"
  - SCRIPT="cd play-scala-fileupload-example     && scripts/test-sbt"
  - SCRIPT="cd play-scala-forms-example          && scripts/test-sbt"
  - SCRIPT="cd play-scala-hello-world-tutorial   && scripts/test-sbt"
  - SCRIPT="cd play-scala-isolated-slick-example && scripts/test-sbt"
  - SCRIPT="cd play-scala-log4j2-example         && scripts/test-sbt"
  - SCRIPT="cd play-scala-macwire-di-example     && scripts/test-sbt"
  - SCRIPT="cd play-scala-rest-api-example       && scripts/test-sbt"
  - SCRIPT="cd play-scala-secure-session-example && scripts/test-sbt"
  - SCRIPT="cd play-scala-slick-example          && scripts/test-sbt"
  - SCRIPT="cd play-scala-starter-example        && scripts/test-sbt"
  - SCRIPT="cd play-scala-streaming-example      && scripts/test-sbt"
  - SCRIPT="cd play-scala-tls-example            && scripts/test-sbt"
  - SCRIPT="cd play-scala-websocket-example      && scripts/test-sbt"

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php && sudo apt-get -qq update && sudo apt-get install -y libsodium-dev # for secure session examples
  - curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install adopt@1.8.202-08 && jabba use "$_" && java -Xmx32m -version

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.jabba/jdk"
    - "$HOME/.sbt"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete
